### PR TITLE
Compose.expand

### PR DESCRIPTION
**Pull request by iaincarsberg**
Hello Kriszyp,

I've been working with compose for a while now, and utterly loving my experience with it. I've recently had an idea on how to expand its functionality.

Its worth nothing that the code I've sent a pull request for likely needs more work doing to it, so see this as more of a work in progress, I'm aware there maybe security implications in regards to my changing the 'constructorsLength' variable, so this maybe a pointless submission.

Firstly I think I need to exemplify its usage, to help it make sense, basically I use compose with RequireJS, so my project organisation consists of lots of small compose files, that are used in a moduler fashion. To make unit testing highly complex objects easier, I've found that breaking functionality down into smaller and smaller blocks helps improve the quality of my code, and as such the ability to expand composed objects is very appealing to me.

To demo this I've prepared the following gist https://gist.github.com/1613428

The general idea is that each area of functionality relating to a specific object can be broken down and tested in separation, then using RequireJS all of the sub modules can be composed into one module, and used as normal.

Feel free to be as critical as you feel the need, as I understand this implementation likely has some flaws.

Thanks
Iain

### CODE REVIEW

**Comment by neonstalwart** [comment]
@iaincarsberg did you have a problem with using extend `Entity = Entity.extend( ... );`?

**Comment by iaincarsberg** [comment]
@neonstalwart My initial though was to use `Entity = Entity.extend(...)` but this isn't going to work with RequireJS in a setup where your decomposing complex objects into multiple files. 

Because when the 'entity.js' which contains  `Entity = Compose(...)` is loaded into the RequireJS namespace a reference is then then parsed to each file that wants to expand its functionality, so when you do `Entity = Entity.extend(...)` its doing an assignment in that local scope, which will only effect the Entity object in the local scope where it was assigned.

I've written another example, this one shows the needs for expand better than the prior one.

// entity.js

```
(function () {
    define(['compose'], function (Compose) {
        return Compose(
            function () {
                this.id = Math.floor(Math.random() * 1000);
            }
        );
    });
}());
```

// entity.expanded.js

```
(function () {
    define(['entity'], function (Entity) {
        // Doing any assignment to Entity here does nothing
        // to the base entity, unless the operation is preformed
        // by the base object on its self, hence the idea
        // behind expand.
    });
}());
```

**Comment by neonstalwart** [comment]
> this isn't going to work with RequireJS in a setup where your decomposing complex objects into multiple files.

it depends on how you approach it.  in the way you've outlined, its not possible but if entity.js pulled together all the pieces that it is composed of then it would work.

entity.js

``` js
define(['compose', 'mixin1', 'mixin2'], function (compose, mixin1, mixin2) {
  return compose(function () {
    this.id = Math.floor(Math.random() * 1000);
  }, mixin1, mixin2);
})
```

without knowing all the restrictions you have in play, i can't say that i can address all of your concerns.  just pointing out that alternatives exist and this is just one - there are even more than this.

**Comment by iaincarsberg** [comment]
I think my requirement is a bit of an edge case, so I'll close the pull request.

What I was trying to implement was a modular system, where subsequent modules can add functionality to a base module, so having a list of components isn't practical from what I can tell, unless I use Compose.call, which is a viable alternative, though that then doesn't use the prototype.

Thanks for taking time to look over my proposal :)

**Pull request closed without merging**
